import type { Metadata } from 'next';
import { Nunito_Sans } from 'next/font/google';
import { Layout } from '@marceloglacial/brinca-ui';
import { NavBar } from '@/components';
import './globals.css';

const inter = Nunito_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Layout header={<NavBar />} footer={<NavBar variant='bottom' />}>
          {children}
        </Layout>
      </body>
    </html>
  );
}
