import type { Metadata } from 'next';
import { Nunito_Sans } from 'next/font/google';
import '../globals.css';
import { Layout } from '@marceloglacial/brinca-ui';
import { NavBar } from '@/components';
import { getMenus } from '@/services';

const inter = Nunito_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Brinca',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const menu = await getMenus();
  const menuItems = menu.data[0].locales[params.locale];
  return (
    <html lang={params.locale}>
      <body className={inter.className}>
        <Layout
          header={<NavBar items={menuItems} />}
          footer={<NavBar items={menuItems} variant='bottom' />}
        >
          {children}
        </Layout>
      </body>
    </html>
  );
}
