import type { Metadata } from 'next';
import { Nunito_Sans } from 'next/font/google';
import '../globals.css';
import { Layout } from '@marceloglacial/brinca-ui';
import { NavBar } from '@/components';
import { getMenus } from '@/services';

const inter = Nunito_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Brinca',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: any;
}>) {
  const menu = await getMenus();
  console.log(menu);

  return (
    <html lang={params.locale}>
      <body className={inter.className}>
        <Layout header={<NavBar />} footer={<NavBar variant='bottom' />}>
          {children}
        </Layout>
      </body>
    </html>
  );
}
