/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    events: Event;
    calendars: Calendar;
    'partner-categories': PartnerCategory;
    partners: Partner;
    mentors: Mentor;
    'mentor-requests': MentorRequest;
    sponsors: Sponsor;
    'ebook-requests': EbookRequest;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    calendars: CalendarsSelect<false> | CalendarsSelect<true>;
    'partner-categories': PartnerCategoriesSelect<false> | PartnerCategoriesSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    mentors: MentorsSelect<false> | MentorsSelect<true>;
    'mentor-requests': MentorRequestsSelect<false> | MentorRequestsSelect<true>;
    sponsors: SponsorsSelect<false> | SponsorsSelect<true>;
    'ebook-requests': EbookRequestsSelect<false> | EbookRequestsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'pt-BR') | ('en' | 'pt-BR')[];
  globals: {};
  globalsSelect: {};
  locale: 'en' | 'pt-BR';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Paste full Cloudinary image URL (https://res.cloudinary.com/...)
   */
  thumbnail?: string | null;
  showInNavbar?: boolean | null;
  /**
   * Mark this page as the site home page
   */
  isHome?: boolean | null;
  components?:
    | (
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'partnerSubmissionBlock';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'mentorSubmissionBlock';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'mentorRequestBlock';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactFormBlock';
          }
        | {
            /**
             * URL used by the success button to download the ebook.
             */
            downloadUrl: string;
            /**
             * Localized disclaimer shown below the email field.
             */
            disclaimerText: string;
            /**
             * Localized text shown next to the optional consent checkbox.
             */
            consentText: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ebookRequestBlock';
          }
        | {
            /**
             * Leave empty to use the current year
             */
            year?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'sponsorsBlock';
          }
        | {
            title?: string | null;
            /**
             * Maximum number of events to display (leave empty for all)
             */
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'eventsListBlock';
          }
        | {
            title?: string | null;
            /**
             * Maximum number of calendar entries to display (leave empty for all)
             */
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'calendarsListBlock';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'partnersListBlock';
          }
        | {
            /**
             * YouTube video URL or video ID
             */
            url: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'youTubeBlock';
          }
        | {
            /**
             * Cloudinary folder path to load images from (e.g. brinca/events/2026)
             */
            cloudinaryFolder: string;
            /**
             * Optional heading displayed above the gallery
             */
            title?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'galleryBlock';
          }
        | {
            url: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'instagramBlock';
          }
        | {
            buttons?:
              | {
                  label?: string | null;
                  style?: ('primary' | 'secondary' | 'link') | null;
                  linkType?: ('internal' | 'external') | null;
                  internalLink?:
                    | ({
                        relationTo: 'pages';
                        value: string | Page;
                      } | null)
                    | ({
                        relationTo: 'events';
                        value: string | Event;
                      } | null)
                    | ({
                        relationTo: 'calendars';
                        value: string | Calendar;
                      } | null);
                  url?: string | null;
                  openInNewWindow?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaBlock';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richTextBlock';
          }
        | {
            title: string;
            description?: string | null;
            /**
             * Paste full Cloudinary or image URL
             */
            image?: string | null;
            direction?: ('left' | 'right') | null;
            cta?: {
              label?: string | null;
              style?: ('primary' | 'secondary' | 'link') | null;
              linkType?: ('internal' | 'external') | null;
              internalLink?:
                | ({
                    relationTo: 'pages';
                    value: string | Page;
                  } | null)
                | ({
                    relationTo: 'events';
                    value: string | Event;
                  } | null)
                | ({
                    relationTo: 'calendars';
                    value: string | Calendar;
                  } | null);
              url?: string | null;
              openInNewWindow?: boolean | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroBlock';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: string;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Paste full Cloudinary image URL (https://res.cloudinary.com/...)
   */
  thumbnail?: string | null;
  /**
   * Event date (non-localized)
   */
  date: string;
  components?:
    | (
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richTextBlock';
          }
        | {
            /**
             * Cloudinary folder path to load images from (e.g. brinca/events/2026)
             */
            cloudinaryFolder: string;
            /**
             * Optional heading displayed above the gallery
             */
            title?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'galleryBlock';
          }
        | {
            url: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'instagramBlock';
          }
        | {
            buttons?:
              | {
                  label?: string | null;
                  style?: ('primary' | 'secondary' | 'link') | null;
                  linkType?: ('internal' | 'external') | null;
                  internalLink?:
                    | ({
                        relationTo: 'pages';
                        value: string | Page;
                      } | null)
                    | ({
                        relationTo: 'events';
                        value: string | Event;
                      } | null)
                    | ({
                        relationTo: 'calendars';
                        value: string | Calendar;
                      } | null);
                  url?: string | null;
                  openInNewWindow?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaBlock';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "calendars".
 */
export interface Calendar {
  id: string;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Paste full Cloudinary image URL (https://res.cloudinary.com/...)
   */
  thumbnail?: string | null;
  /**
   * Event date (non-localized)
   */
  date: string;
  components?:
    | (
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richTextBlock';
          }
        | {
            /**
             * Cloudinary folder path to load images from (e.g. brinca/events/2026)
             */
            cloudinaryFolder: string;
            /**
             * Optional heading displayed above the gallery
             */
            title?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'galleryBlock';
          }
        | {
            url: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'instagramBlock';
          }
        | {
            buttons?:
              | {
                  label?: string | null;
                  style?: ('primary' | 'secondary' | 'link') | null;
                  linkType?: ('internal' | 'external') | null;
                  internalLink?:
                    | ({
                        relationTo: 'pages';
                        value: string | Page;
                      } | null)
                    | ({
                        relationTo: 'events';
                        value: string | Event;
                      } | null)
                    | ({
                        relationTo: 'calendars';
                        value: string | Calendar;
                      } | null);
                  url?: string | null;
                  openInNewWindow?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaBlock';
          }
        | {
            /**
             * YouTube video URL or video ID
             */
            url: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'youTubeBlock';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partner-categories".
 */
export interface PartnerCategory {
  id: string;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: string;
  title: string;
  description: string;
  /**
   * Paste full Cloudinary or image URL
   */
  logo?: string | null;
  category: string | PartnerCategory;
  status: 'pending' | 'active' | 'rejected';
  active?: boolean | null;
  contact?: {
    email?: string | null;
    phone?: string | null;
    whatsapp?: string | null;
    address?: string | null;
  };
  website?: string | null;
  social?: {
    facebook?: string | null;
    instagram?: string | null;
    linkedin?: string | null;
  };
  /**
   * Email registered as a BRINCA member
   */
  membershipEmail?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mentors".
 */
export interface Mentor {
  id: string;
  name: string;
  email: string;
  phone: string;
  inCanadaSince: string;
  /**
   * Do you have school-age children? How many and what age?
   */
  hasChildren: string;
  /**
   * Briefly describe your professional profile and why you would like to be a mentor/sponsor for a newcomer
   */
  profile: string;
  status: 'pending' | 'active' | 'rejected';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mentor-requests".
 */
export interface MentorRequest {
  id: string;
  name: string;
  email: string;
  phone: string;
  plannedTravelDate: string;
  /**
   * How long do you plan to stay in Ottawa?
   */
  stayDuration: string;
  /**
   * Briefly describe your family, your immigration status (student, PR, etc.), and what you expect from a sponsor
   */
  familyDescription: string;
  status: 'pending' | 'active' | 'rejected';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors".
 */
export interface Sponsor {
  id: string;
  name: string;
  /**
   * Paste full Cloudinary or image URL
   */
  logo?: string | null;
  website?: string | null;
  tier: 'diamond' | 'silver' | 'bronze';
  /**
   * Year this sponsorship applies to (e.g. 2026)
   */
  year: number;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ebook-requests".
 */
export interface EbookRequest {
  id: string;
  name: string;
  email: string;
  consentGiven?: boolean | null;
  status: 'pending' | 'processed' | 'rejected';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'events';
        value: string | Event;
      } | null)
    | ({
        relationTo: 'calendars';
        value: string | Calendar;
      } | null)
    | ({
        relationTo: 'partner-categories';
        value: string | PartnerCategory;
      } | null)
    | ({
        relationTo: 'partners';
        value: string | Partner;
      } | null)
    | ({
        relationTo: 'mentors';
        value: string | Mentor;
      } | null)
    | ({
        relationTo: 'mentor-requests';
        value: string | MentorRequest;
      } | null)
    | ({
        relationTo: 'sponsors';
        value: string | Sponsor;
      } | null)
    | ({
        relationTo: 'ebook-requests';
        value: string | EbookRequest;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  thumbnail?: T;
  showInNavbar?: T;
  isHome?: T;
  components?:
    | T
    | {
        partnerSubmissionBlock?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        mentorSubmissionBlock?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        mentorRequestBlock?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        contactFormBlock?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        ebookRequestBlock?:
          | T
          | {
              downloadUrl?: T;
              disclaimerText?: T;
              consentText?: T;
              id?: T;
              blockName?: T;
            };
        sponsorsBlock?:
          | T
          | {
              year?: T;
              id?: T;
              blockName?: T;
            };
        eventsListBlock?:
          | T
          | {
              title?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        calendarsListBlock?:
          | T
          | {
              title?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        partnersListBlock?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        youTubeBlock?:
          | T
          | {
              url?: T;
              id?: T;
              blockName?: T;
            };
        galleryBlock?:
          | T
          | {
              cloudinaryFolder?: T;
              title?: T;
              id?: T;
              blockName?: T;
            };
        instagramBlock?:
          | T
          | {
              url?: T;
              id?: T;
              blockName?: T;
            };
        ctaBlock?:
          | T
          | {
              buttons?:
                | T
                | {
                    label?: T;
                    style?: T;
                    linkType?: T;
                    internalLink?: T;
                    url?: T;
                    openInNewWindow?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        richTextBlock?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        heroBlock?:
          | T
          | {
              title?: T;
              description?: T;
              image?: T;
              direction?: T;
              cta?:
                | T
                | {
                    label?: T;
                    style?: T;
                    linkType?: T;
                    internalLink?: T;
                    url?: T;
                    openInNewWindow?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  thumbnail?: T;
  date?: T;
  components?:
    | T
    | {
        richTextBlock?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        galleryBlock?:
          | T
          | {
              cloudinaryFolder?: T;
              title?: T;
              id?: T;
              blockName?: T;
            };
        instagramBlock?:
          | T
          | {
              url?: T;
              id?: T;
              blockName?: T;
            };
        ctaBlock?:
          | T
          | {
              buttons?:
                | T
                | {
                    label?: T;
                    style?: T;
                    linkType?: T;
                    internalLink?: T;
                    url?: T;
                    openInNewWindow?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "calendars_select".
 */
export interface CalendarsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  thumbnail?: T;
  date?: T;
  components?:
    | T
    | {
        richTextBlock?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        galleryBlock?:
          | T
          | {
              cloudinaryFolder?: T;
              title?: T;
              id?: T;
              blockName?: T;
            };
        instagramBlock?:
          | T
          | {
              url?: T;
              id?: T;
              blockName?: T;
            };
        ctaBlock?:
          | T
          | {
              buttons?:
                | T
                | {
                    label?: T;
                    style?: T;
                    linkType?: T;
                    internalLink?: T;
                    url?: T;
                    openInNewWindow?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        youTubeBlock?:
          | T
          | {
              url?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partner-categories_select".
 */
export interface PartnerCategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  logo?: T;
  category?: T;
  status?: T;
  active?: T;
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        whatsapp?: T;
        address?: T;
      };
  website?: T;
  social?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        linkedin?: T;
      };
  membershipEmail?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mentors_select".
 */
export interface MentorsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  inCanadaSince?: T;
  hasChildren?: T;
  profile?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mentor-requests_select".
 */
export interface MentorRequestsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  plannedTravelDate?: T;
  stayDuration?: T;
  familyDescription?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors_select".
 */
export interface SponsorsSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  website?: T;
  tier?: T;
  year?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ebook-requests_select".
 */
export interface EbookRequestsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  consentGiven?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}